GerenciadorDePoliticasDeCompliance/GerenciadorDePoliticasDeCompliance.Web/Controllers/FuncionariosController.cs
using GerenciadorDePoliticasDeCompliance.Core.BancoDeDados;
using GerenciadorDePoliticasDeCompliance.Core.Dominio;
using GerenciadorDePoliticasDeCompliance.Models.Funcionarios;
using GerenciadorDePoliticasDeCompliance.Web.Models.Funcionarios;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data.SqlClient;

namespace GerenciadorDePoliticasDeCompliance.Controllers
{

    [Authorize(Roles = "Administrador")]
    public class FuncionariosController : Controller
    {
        private Conexao Conexao { get; set; }
        public FuncionariosController()
        {
            Conexao = new Conexao();
        }
        public IActionResult Index()
        {
            ListaViewModel lista = new ListaViewModel();
            var comandosql = new SqlCommand(Queries.QUERY_LISTAR_FUNCIONARIOS);
            var dataReader = Conexao.Consultar(comandosql);
            if (dataReader.HasRows)
            {
                while (dataReader.Read())
                {
                    var id = int.Parse(dataReader["Id"].ToString());
                    var nome = dataReader["Nome"].ToString();
                    var cpf = int.Parse(dataReader["CPF"].ToString());
                    var matricula = int.Parse(dataReader["Matricula"].ToString());
                    var email = dataReader["Email"].ToString();
                    lista.Funcionarios.Add(new FuncionarioDaListaViewModel(id, nome, cpf, matricula, email));
                }
            }
            return View(lista);
        }

        [AllowAnonymous]
        public IActionResult Formulario()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Cadastrar(FormularioViewModel modelo)
        {
                    
            Funcionario funcionario = modelo.ConverterParaFuncionario();
            Usuario usuario = modelo.ConverterParaUsuario();

            var comandosql = new SqlCommand(Queries.QUERY_CADASTRO_USUARIO);
            comandosql.Parameters.AddWithValue("@Email", usuario.Email);
            comandosql.Parameters.AddWithValue("@Senha", usuario.Senha);
            comandosql.Parameters.AddWithValue("@IdPerfil", (int)usuario.Perfil);
            int idusuario = Conexao.ExecutarQuery(comandosql);
            comandosql = new SqlCommand(Queries.QUERY_CADASTRO_FUNCIONARIO);
            comandosql.Parameters.AddWithValue("@Nome", funcionario.Nome);
            comandosql.Parameters.AddWithValue("@CPF", funcionario.CPF);
            comandosql.Parameters.AddWithValue("@Matricula", funcionario.Matricula);
            comandosql.Parameters.AddWithValue("@Email", funcionario.Email);
            comandosql.Parameters.AddWithValue("@IdUsuario", idusuario);
            Conexao.ExecutarQuery(comandosql);
            TempData["CadastroRealizadoComSUcesso"] = "Cadastrado com sucesso!";

            return RedirectToAction("Index", "Login");
        }

        public IActionResult Assinantes(int id)
        {
            ListaViewModel listaidfuncionarios = new ListaViewModel();
            List<string> idfuncionarios = new List<string>();
            var comandosql = new SqlCommand(Queries.QUERY_LISTAR_IDPOLITICA_ASSINANTES);
            comandosql.Parameters.AddWithValue("@IdPolitica", id);
            var dataReader = Conexao.Consultar(comandosql);
            if (dataReader.HasRows)
            {
                while (dataReader.Read())
                {

                    var id2 = dataReader["IdFuncionario"].ToString();

                    idfuncionarios.Add(id2);
                }
            }
            Conexao._conexao.Close();
            foreach (string obj in idfuncionarios)
            {

                comandosql = new SqlCommand(Queries.QUERY_LISTAR_ID_FUNCIONARIOS);
                comandosql.Parameters.AddWithValue("@Id", obj);
                dataReader = Conexao.Consultar(comandosql);

                dataReader.Read();
                var idfun = int.Parse(dataReader["Id"].ToString());
                var nome = dataReader["Nome"].ToString();
                var cpf = int.Parse(dataReader["CPF"].ToString());
                var matricula = int.Parse(dataReader["Matricula"].ToString());
                var email = dataReader["Email"].ToString();
                listaidfuncionarios.Funcionarios.Add(new FuncionarioDaListaViewModel(idfun, nome, cpf, matricula, email));
                Conexao._conexao.Close();
            }
            return View("Index", listaidfuncionarios);
        }
    }
}

GerenciadorDePoliticasDeCompliance/GerenciadorDePoliticasDeCompliance.Web/Controllers/PoliticasController.cs
using GerenciadorDePoliticasDeCompliance.Web.Models.Politicas;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using GerenciadorDePoliticasDeCompliance.Core.BancoDeDados;
using System;
using GerenciadorDePoliticasDeCompliance.Core.Dominio;
using Microsoft.AspNetCore.Authorization;

namespace GerenciadorDePoliticasDeCompliance.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class PoliticasController : Controller
    {
        private Conexao Conexao { get; set; }
        public PoliticasController()
        {
            Conexao = new Conexao();
        }
        
        public IActionResult Index()
        {
            ListaViewModel lista = new ListaViewModel();
            var comandosql = new SqlCommand(Queries.QUERY_LISTAR_POLITICA);
            var dataReader = Conexao.Consultar(comandosql);
            if (dataReader.HasRows)
            {
                while (dataReader.Read())
                {
                    var id = int.Parse(dataReader["Id"].ToString());
                    var titulo = dataReader["Titulo"].ToString();
                    var data = DateTime.Parse(dataReader["Data"].ToString());

                    lista.Politicas.Add(new PoliticaDaListaViewModel(id, titulo, data.ToString("dd/MM/yyyy")));
                }
            }
            return View(lista);
        }

        public IActionResult Detalhes(int id)
        {
            ListaViewModel detalhes = new ListaViewModel();
            var comandosql = new SqlCommand(Queries.QUERY_LISTAR_ID_POLITICA);
            comandosql.Parameters.AddWithValue("@Id", id);
            var dataReader = Conexao.Consultar(comandosql);
            dataReader.Read();
            var titulo = dataReader["Titulo"].ToString();
            var texto = dataReader["Texto"].ToString();
            detalhes.Politicas.Add(new PoliticaDaListaViewModel(titulo, texto, id));
            return View(detalhes);
        }

        public IActionResult Formulario()
        {
            return View(new FormularioViewModel());
        }


        [HttpPost]
        public IActionResult Salvar(FormularioViewModel modelo)
        {
            SqlCommand comandosql = null;
            Politica politica = modelo.ConverterParaPolitica();
            if (modelo.Id == 0)
            {
                comandosql = new SqlCommand(Queries.QUERY_CADASTRO_POLITICAS);
                comandosql.Parameters.AddWithValue("@Titulo", politica.Titulo);
                comandosql.Parameters.AddWithValue("@Texto", politica.Texto);
                comandosql.Parameters.AddWithValue("@Data", DateTime.Now);
                TempData["PoliticaAdicionada"] = "Política adicionada com sucesso!";
            }
            else
            {
                comandosql = new SqlCommand(Queries.QUERY_DELETAR_ASSINATURAPOLITICA);
                comandosql.Parameters.AddWithValue("Id", politica.Id);
                Conexao.ExecutarQuery(comandosql);
                Conexao._conexao.Close();
                comandosql = new SqlCommand(Queries.QUERY_ATUALIZAR_POLITICA);
                comandosql.Parameters.AddWithValue("@Id", modelo.Id);
                comandosql.Parameters.AddWithValue("@Titulo", politica.Titulo);
                comandosql.Parameters.AddWithValue("@Texto", politica.Texto);
                comandosql.Parameters.AddWithValue("@Data", DateTime.Now);
                TempData["PoliticaEditada"] = "Política editada com sucesso!";
            }
            Conexao.ExecutarQuery(comandosql);
            return RedirectToAction("Index");
        }

        public IActionResult Edicao(int id)
        {
            var comandosql = new SqlCommand(Queries.QUERY_LISTAR_ID_POLITICA);
            comandosql.Parameters.AddWithValue("@Id", id);
            var dataReader = Conexao.Consultar(comandosql);
            dataReader.Read();
            var titulo = dataReader["Titulo"].ToString();
            var texto = dataReader["Texto"].ToString();
            FormularioViewModel formulario = new FormularioViewModel(id, titulo, texto);
            return View("Formulario", formulario);
        }

        public IActionResult Deletar(int id)
        {
            var comandosql = new SqlCommand(Queries.QUERY_DELETAR_POLITICA);
            comandosql.Parameters.AddWithValue("@Id", id);
            Conexao.ExecutarQuery(comandosql);
            return RedirectToAction("Index");
        }



    }
}

GerenciadorDePoliticasDeCompliance/GerenciadorDePoliticasDeCompliance.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GerenciadorDePoliticasDeCompliance</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-flatly.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" type="image/png" href="~/imagens/sejavocenawiz-1538432208-zpng.png" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (Context.User.IsInRole("Administrador"))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Politicas" asp-action="Index">GerenciadorDePoliticasDeCompliance</a>

                }
                @if (Context.User.IsInRole("Funcionario"))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GerenciadorDePoliticasDeCompliance</a>
                }

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            @if (Context.User.IsInRole("Administrador"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionarios</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Politicas" asp-action="Index">Politicas</a>
                                </li>
                            }
                            @if (Context.User.IsInRole("Funcionario"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Politicas</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Deslogar">Deslogar</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">

        <div class="container">

            &copy; 2020 - GerenciadorDePoliticasDeCompliance  </a>
        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>
}